"""Read-only health checks for Artjeck's local lab and projects."""
from __future__ import annotations

import json
import os
import plistlib
import re
import subprocess
import urllib.error
import urllib.request
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from urllib.parse import urlparse

from .config import cfg
from .project_context import discover_project_roots


@dataclass(frozen=True)
class HealthCheck:
    name: str
    status: str
    detail: str
    command: str = ""
    duration_ms: int = 0


def health_dir(root: Path | None = None) -> Path:
    return root or cfg.state_db.parent / "health"


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def deployed_labels() -> list[str]:
    """The launchd labels this repository actually ships, read from its plists.

    The label was hardcoded, so the report could be green for a service that was
    never installed while the ones that exist were down. Reading `deploy/` means
    the check follows the deployment instead of a string written once.
    """
    labels: list[str] = []
    deploy = _repo_root() / "deploy"
    for path in sorted(deploy.rglob("*.plist*")):
        try:
            raw = path.read_bytes()
            # .template files carry placeholders that are not valid plist values.
            if path.suffix == ".template" or b"__" in raw:
                match = re.search(rb"<key>Label</key>\s*<string>([^<]+)</string>", raw)
                if match:
                    labels.append(match.group(1).decode())
                continue
            labels.append(plistlib.loads(raw)["Label"])
        except Exception:
            continue
    # The overnight job's plist is generated by its installer, so its label lives
    # in the script rather than in a file we can parse.
    for script in sorted(deploy.glob("install-*.sh")):
        match = re.search(r'^LABEL="([^"]+)"', script.read_text(), re.MULTILINE)
        if match:
            labels.append(match.group(1))
    return sorted(set(labels))


def _state_path(root: Path) -> Path:
    return root / "last-run.json"


def _previous(root: Path) -> dict[str, str] | None:
    path = _state_path(root)
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text())
    except json.JSONDecodeError:
        return None


def _transitions(previous: dict[str, str] | None, checks: list[HealthCheck]) -> dict:
    """What changed since last night — which is the only part worth alerting on.

    A report of current state is one nobody reads by the third morning: this
    system printed an identical "2 failed" for weeks, and both failures were
    permanent by construction, so a real outage would have looked the same.
    """
    if previous is None:
        return {"new_fail": [], "recovered": [], "unchanged": [c.name for c in checks], "first_run": True}
    new_fail, recovered, unchanged = [], [], []
    for check in checks:
        was = previous.get(check.name)
        if was is None:
            unchanged.append(check.name)
        elif check.status == "fail" and was != "fail":
            new_fail.append(check.name)
        elif was == "fail" and check.status == "pass":
            recovered.append(check.name)
        else:
            unchanged.append(check.name)
    return {"new_fail": new_fail, "recovered": recovered, "unchanged": unchanged, "first_run": False}


def latest_health_report(root: Path | None = None) -> Path | None:
    base = health_dir(root)
    if not base.exists():
        return None
    reports = sorted(base.glob("*.md"), key=lambda path: path.stat().st_mtime, reverse=True)
    return reports[0] if reports else None


def run_health(*, output_dir: Path | None = None, timeout_s: int = 45, include_projects: bool = False) -> dict:
    """Probe this system's own services; optionally also run other projects' suites.

    `include_projects` is off by default and the nightly does not pass it.
    Discovering repositories from the ingest targets and running their test and
    build commands is neither read-only nor this program's job — and the child
    inherits this process's environment, which `config` has already filled from
    `.env`. Project QA belongs to the QA system; this stays a health check.
    """
    checks: list[HealthCheck] = []
    checks.extend(_service_checks(timeout_s=min(timeout_s, 10)))
    if include_projects:
        checks.extend(_project_checks(timeout_s=timeout_s))

    out_dir = health_dir(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    transitions = _transitions(_previous(out_dir), checks)
    stamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    report = out_dir / f"{stamp}-health.md"
    markdown = render_health_report(stamp=stamp, checks=checks, transitions=transitions)
    report.write_text(markdown)
    _state_path(out_dir).write_text(json.dumps({c.name: c.status for c in checks}, indent=2) + "\n")
    return {
        "transitions": transitions,
        "path": str(report),
        "checks": [check.__dict__ for check in checks],
        "passed": sum(1 for check in checks if check.status == "pass"),
        "failed": sum(1 for check in checks if check.status == "fail"),
        "skipped": sum(1 for check in checks if check.status == "skip"),
        "markdown": markdown,
    }


def render_health_report(*, stamp: str, checks: list[HealthCheck], transitions: dict | None = None) -> str:
    passed = sum(1 for check in checks if check.status == "pass")
    failed = sum(1 for check in checks if check.status == "fail")
    skipped = sum(1 for check in checks if check.status == "skip")
    lines = [
        f"# Health Report - {stamp}",
        "",
    ]
    if transitions is not None:
        if transitions.get("first_run"):
            lines.append("- Changes: none to compare — no previous run recorded")
        elif transitions["new_fail"] or transitions["recovered"]:
            if transitions["new_fail"]:
                lines.append(f"- **{len(transitions['new_fail'])} check(s) newly failing**: {', '.join(transitions['new_fail'])}")
            if transitions["recovered"]:
                lines.append(f"- {len(transitions['recovered'])} check(s) recovered: {', '.join(transitions['recovered'])}")
        else:
            lines.append("- Changes: none since the last run")
        lines.append("")
    lines += [
        f"- Passed: {passed}",
        f"- Failed: {failed}",
        f"- Skipped: {skipped}",
        "",
        "## Checks",
        "",
    ]
    for check in checks:
        lines.append(f"- {check.status.upper()} {check.name}: {check.detail}")
        if check.command:
            lines.append(f"  - Command: `{check.command}`")
        if check.duration_ms:
            lines.append(f"  - Duration: {check.duration_ms} ms")
    return "\n".join(lines).rstrip() + "\n"


def _service_checks(timeout_s: int) -> list[HealthCheck]:
    """Ask each configured dependency whether it is up — and ask nothing else.

    This used to probe Ollama's native `/api/tags` whatever `OPENAI_BASE_URL`
    pointed at, so every night the gateway answered 404 and the report said
    "FAIL ollama" about a service that was fine. A check that is always red is a
    check nobody reads, which is how a genuinely red CI went unnoticed for two
    weeks. Qdrant is likewise only probed when it is the configured store.
    """
    checks = [_http_check("llm", _llm_url(), timeout_s=timeout_s)]
    if cfg.store_backend == "qdrant":
        checks.append(_http_check("qdrant", cfg.qdrant_url.rstrip("/") + "/collections", timeout_s=timeout_s))
    else:
        checks.append(
            HealthCheck(name="store", status="pass", detail=f"{cfg.store_backend} at {cfg.persist_dir}")
        )
    for label in deployed_labels() or ["com.secondbrain.overnight"]:
        checks.append(_launchd_check(label))
    return checks


def _llm_url() -> str:
    """The OpenAI-compatible model list: answered by Ollama and by the gateway alike."""
    base = cfg.base_url.rstrip("/")
    if base.endswith("/v1"):
        return base + "/models"
    parsed = urlparse(cfg.base_url)
    origin = f"{parsed.scheme}://{parsed.netloc}" if parsed.scheme and parsed.netloc else base
    return origin.rstrip("/") + "/v1/models"


def _http_check(name: str, url: str, *, timeout_s: int) -> HealthCheck:
    start = datetime.now()
    try:
        headers = {}
        if name == "qdrant" and cfg.qdrant_api_key:
            headers["api-key"] = cfg.qdrant_api_key
        if name == "llm" and cfg.api_key:
            headers["Authorization"] = f"Bearer {cfg.api_key}"
        request = urllib.request.Request(url, headers=headers)
        with urllib.request.urlopen(request, timeout=timeout_s) as response:
            status = getattr(response, "status", 200)
            ok = 200 <= int(status) < 300
            detail = f"HTTP {status} at {url}"
            return HealthCheck(name=name, status="pass" if ok else "fail", detail=detail, duration_ms=_elapsed_ms(start))
    except (urllib.error.URLError, TimeoutError, OSError) as exc:
        return HealthCheck(name=name, status="fail", detail=f"{url}: {exc}", duration_ms=_elapsed_ms(start))


def _launchd_check(label: str) -> HealthCheck:
    res = _run(["launchctl", "list"], cwd=Path.home(), timeout_s=10)
    if res.returncode != 0:
        return HealthCheck(name=f"launchd {label}", status="fail", detail=res.output, command=res.command, duration_ms=res.duration_ms)
    loaded = label in res.output
    return HealthCheck(
        name=f"launchd {label}",
        status="pass" if loaded else "fail",
        detail=f"{label} {'loaded' if loaded else 'not loaded'}",
        command=res.command,
        duration_ms=res.duration_ms,
    )


def _project_checks(timeout_s: int) -> list[HealthCheck]:
    checks = []
    for root in discover_project_roots(limit=12):
        checks.append(_project_check(root, timeout_s=timeout_s))
    return checks


def _project_check(root: Path, *, timeout_s: int) -> HealthCheck:
    command = _project_command(root)
    if not command:
        return HealthCheck(name=f"project {root.name}", status="skip", detail=f"no safe test/build command found ({root})")
    res = _run(command, cwd=root, timeout_s=timeout_s)
    status = "pass" if res.returncode == 0 else "fail"
    detail = _summarize_output(res.output)
    return HealthCheck(
        name=f"project {root.name}",
        status=status,
        detail=detail,
        command=res.command,
        duration_ms=res.duration_ms,
    )


def _project_command(root: Path) -> list[str]:
    pyproject = root / "pyproject.toml"
    if pyproject.exists() and (root / "tests").exists():
        if (root / "uv.lock").exists():
            return ["uv", "run", "pytest"]
        return ["python3", "-m", "pytest"]
    package = root / "package.json"
    if package.exists():
        try:
            scripts = json.loads(package.read_text()).get("scripts", {})
        except Exception:
            scripts = {}
        if "test" in scripts:
            return ["npm", "test"]
        if "build" in scripts:
            return ["npm", "run", "build"]
    return []


@dataclass(frozen=True)
class _RunResult:
    command: str
    returncode: int
    output: str
    duration_ms: int


def _run(command: list[str], *, cwd: Path, timeout_s: int) -> _RunResult:
    start = datetime.now()
    try:
        proc = subprocess.run(
            command,
            cwd=str(cwd),
            text=True,
            capture_output=True,
            timeout=timeout_s,
            env=_clean_env(),
        )
        output = "\n".join(part for part in [proc.stdout.strip(), proc.stderr.strip()] if part)
        return _RunResult(" ".join(command), proc.returncode, output, _elapsed_ms(start))
    except subprocess.TimeoutExpired as exc:
        output = "\n".join(
            part.decode() if isinstance(part, bytes) else part
            for part in [exc.stdout, exc.stderr]
            if part
        ).strip()
        return _RunResult(" ".join(command), 124, f"timed out after {timeout_s}s\n{output}".strip(), _elapsed_ms(start))
    except OSError as exc:
        return _RunResult(" ".join(command), 127, str(exc), _elapsed_ms(start))


def _elapsed_ms(start: datetime) -> int:
    return int((datetime.now() - start).total_seconds() * 1000)


def _clean_env() -> dict[str, str]:
    """The child's environment, with this process's secrets removed.

    `config` calls `load_dotenv()` at import, so by the time a check runs, the
    API key, the store key and the MCP token are all in `os.environ`. A test
    command in someone else's repository has no business receiving them.
    """
    env = os.environ.copy()
    env.pop("VIRTUAL_ENV", None)
    for name in list(env):
        if any(marker in name.upper() for marker in ("API_KEY", "TOKEN", "SECRET", "PASSWORD")):
            env.pop(name, None)
    return env


def _summarize_output(output: str, limit: int = 500) -> str:
    text = " ".join(output.split())
    if not text:
        return "no output"
    if len(text) <= limit:
        return text
    return text[: limit - 3].rsplit(" ", 1)[0] + "..."
